file_mappings:
  ABBESTBEI.csv:
  ABSENDER.csv: 
  ABTEIL.csv: 
  ADRESS.csv: 
  AENDART.csv: 
  AENDLOG.csv: 
  AHAPLA.csv: 
  AHLIEF.csv: 
  ANABFMDE.csv: 
  ANABMELD.csv:
  ANFKO.csv: 
  ANFPO.csv: 
  ANGKO.csv:
  ANGPO.csv:
  ANGTXT.csv:
  ANNAHMKO.csv: 
  ANNAHMPO.csv: 
  ANREDEN.csv: 
  ANZRECH.csv: 
  APLRUEST.csv: 
  APLZSTAF.csv: 
  APPAngko.csv: 
  APPAngpo.csv: 
  APPAufko.csv: 
  APPAufpo.csv: 
  APPUser.csv: 
  ARBGANG.csv: 
  ARBPLAPM.csv: 
  ARBPLAPO.csv: 
  ARBPLAWZN.csv: 
  ARBPLPRS.csv: 
  ARBTEXT.csv: 
  ARCHUEB.csv: 
  ARTDOK.csv: 
  ARTGRU.csv: 
  ARTKGRPR.csv: 
  ARTKOMP.csv: 
  ARTLEBEN.csv: 
  ARTLIEF.csv: 
  ARTSPERR.csv: 
  ARTST.csv: 
  ARTST2.csv: 
  ARTSUCH.csv: 
  AUFAEND.csv: 
  AUFKO.csv: 
  AUFPO.csv: 
  AUFPOV.csv: 
  AUFSCHL.csv: 
  AUFSTAT.csv: 
  AUFTERM.csv: 
  AUFTXT.csv: 
  AUSARB.csv: 
  AUSFERKL.csv: 
  AUSGRUND.csv: 
  AUSLAST.csv: 
  AUTOANF.csv: 
  AUTOBEST.csv: 
  AUTOBET.csv: 
  AVWORKFL.csv: 
  BAABGL.csv: 
  BAAUSARB.csv: 
  BAB.csv: 
  BAKOMM.csv: 
  BANKEN.csv: 
  BARCODES.csv: 
  BAVORBER.csv: 
  BDEDAT.csv: 
  BDELABEL.csv: 
  BDEVERAG.csv: 
  BDEVERS.csv: 
  BELAKO.csv: 
  BELAPO.csv: 
  BELATXT.csv: 
  BEMELD.csv: 
  BEMELDBEI.csv: 
  BEMELDLG.csv: 
  BEMELDPO.csv: 
  BEMELDV.csv: 
  BEMELSER.csv: 
  BEMELSNB.csv: 
  BEMELUSB.csv: 
  BEMELUSR.csv: 
  BESTAEND.csv: 
  BESTBEI.csv: 
  BESTKO.csv: 
  BESTPO.csv: 
  BESTPO2.csv: 
  BESTSTAT.csv: 
  BESTTXT.csv: 
  BETAPLA.csv: 
  BETAPLAM.csv: 
  BETAPLAS.csv: 
  BETAPPRS.csv: 
  BETAUF.csv: 
  BETAUFAR.csv: 
  BETAUFKO.csv: 
  BETETI.csv: 
  BETLIPLA.csv: 
  BETMELD.csv: 
  BETNACH.csv: 
  BETPRUEF.csv: 
  BETSTULI.csv: 
  BILDARCH.csv: 
  BLECH.csv: 
  BLZST.csv: 
  BRANCODE.csv: 
  CAPAPOS.csv: 
  CHAOSHIS.csv: 
  CHAOSLAG.csv: 
  CHARGEN.csv: 
  CHARGRU.csv: 
  CHARTXT.csv: 
  CLCODE.csv: 
  CRSMEDIA.csv: 
  CSUPPKO.csv: 
  CSUPPPO.csv: 
  DATEVHLP.csv: 
  DECKUNG.csv: 
  DHRDAT.csv: 
  DIGSIGLOG.csv: 
  DISPOGRU.csv: 
  DOKUMENT.csv: 
  DOKUTEXT.csv: 
  DPD.csv: 
  DTVPRIMA.csv: 
  EDIKOPF.csv: 
  EDIORDK.csv: 
  EDIORDP.csv: 
  EDIORDT.csv: 
  EDIPART.csv: 
  EDIPOS.csv: 
  EDIPROF.csv: 
  EDITEXT.csv: 
  EKGENOSS.csv: 
  ENDPRUEF.csv: 
  ENTBER.csv: 
  ERSVER.csv: 
  EXPTEXT.csv: 
  EXTPRG.csv: 
  FACHRICH.csv: 
  FARTTXT.csv: 
  FDANR.csv: 
  FEHLKAT.csv: 
  FEHLTAGE.csv: 
  FEHLTEXT.csv: 
  FEIERTAG.csv: 
  FELDEINS.csv: 
  FERTKO.csv: 
  FRACHT.csv: 
  FREMDREP.csv: 
  GEBRPO.csv: 
  GEBRST.csv: 
  GELATXT.csv: 
  GKVOR.csv: 
  HAERTPR.csv: 
  HANDBED.csv: 
  HARBPLAPO.csv: 
  HOTEL.csv: 
  HPRUEFPO.csv: 
  HRLAGER.csv: 
  HSTULIPO.csv: 
  IMPORTKO.csv: 
  IMPORTPO.csv: 
  IMPPROT.csv: 
  INKASSO.csv: 
  INTTEST.csv: 
  INVLOG.csv: 
  INVPERM.csv: 
  JOB.csv: 
  JOBPRIO.csv: 
  KABELBW.csv: 
  KALAPLA.csv: 
  KALAPPRS.csv: 
  KALEND2.csv: 
  KALENDER.csv: 
  KALKOPF2.csv: 
  KALKULAT.csv: 
  KALLEIST.csv: 
  KALRUEST.csv: 
  KALSTULI.csv: 
  KALWERK.csv: 
  KAPAPROF.csv: 
  KAPFARB.csv: 
  KDANF.csv: 
  KDANFLOG.csv: 
  KDERLKTO.csv: 
  KDGRU.csv: 
  KDGRURAB.csv: 
  KDLIEF.csv: 
  KDMASCH.csv: 
  KDPARAM.csv: 
  KDREF.csv: 
  KDSPERR.csv: 
  KDST.csv: 
  KDST2.csv: 
  KENNZTAB.csv: 
  KONSILAG.csv: 
  KONTAKTK.csv: 
  KONTAKTL.csv: 
  KONTBETR.csv: 
  KONTBST.csv: 
  KONZERN.csv: 
  KORRMASS.csv: 
  KOSTART.csv: 
  KOSTGRU.csv: 
  KOSTST.csv: 
  KOSTTR.csv: 
  KOSTWART.csv: 
  KUNDANSP.csv: 
  LAGER.csv: 
  LAGHIST.csv: 
  LAGPLATZ.csv: 
  LAGPLPOS.csv: 
  LANDTAB.csv: 
  LEBENTXT.csv: 
  LEIHHIPR.csv: 
  LEIHHIST.csv: 
  LEIHKOMP.csv: 
  LEIHKOPR.csv: 
  LEIHRESK.csv: 
  LEIHRESP.csv: 
  LEIHSEPR.csv: 
  LEIHSET.csv: 
  LFDNR1.csv: 
  LFDNR2.csv: 
  LFDNR3.csv: 
  LGVERWEND.csv: 
  LIEFADR.csv: 
  LIEFANSP.csv: 
  LIEFBED.csv: 
  LIEFGRU.csv: 
  LIEFKO.csv: 
  LIEFPO.csv: 
  LIEFPOC.csv: 
  LIEFPOV.csv: 
  LIEFRECH.csv: 
  LIEFSPERR.csv: 
  LIEFST.csv: 
  LIEFSUCH.csv: 
  LIEFTXT.csv: 
  LIPLAPO.csv: 
  LOGBUCH.csv: 
  LOGPASS.csv: 
  LOHNGRU.csv: 
  MAHNLIEF.csv: 
  MAHNLOG.csv: 
  MAHNTXK2.csv: 
  MAHNTXTD.csv: 
  MAHNTXTK.csv: 
  MASCHBLG.csv: 
  MASCHFR.csv: 
  MASCHGRU.csv: 
  MASCHKO.csv: 
  MASCHPLA.csv: 
  MATKO.csv: 
  MDEIMP.csv: 
  MDEIMP2.csv: 
  MENGTAB.csv: 
  MENUSKIP.csv: 
  MERKGRU.csv: 
  MESSGER.csv: 
  MESSGRU.csv: 
  MESSKOST.csv: 
  MINDMENG.csv: 
  MOTIV.csv: 
  MUSTER.csv: 
  MWSTTAB.csv: 
  NACHARB.csv: 
  NOTIZ.csv: 
  PARAHIST.csv: 
  PASSWORT.csv: 
  PAUSENST.csv: 
  PDALOG.csv: 
  PERLEBEN.csv: 
  PERSGRU.csv: 
  PERSONAL.csv: 
  PGRUZUO.csv: 
  PLZST.csv: 
  PRODDOKU.csv: 
  PRODMELD.csv: 
  PRODPLA1.csv: 
  PROGTAB.csv: 
  PROJART.csv: 
  PROJDOK.csv: 
  PROJHIST.csv: 
  PROJKO.csv: 
  PROJPO.csv: 
  PROJTEAM.csv: 
  PROJZULA.csv: 
  PROVSTAF.csv: 
  PRUEFANW.csv: 
  PRUEFBDE.csv: 
  PRUEFHIS.csv: 
  PRUEFPO.csv: 
  PZELABEL.csv: 
  PZESALDO.csv: 
  QUALIFIK.csv: 
  QUARUMS.csv: 
  RABATTE.csv: 
  RECHKO.csv: 
  RECHPO.csv: 
  RECHTXT.csv: 
  REFUEB.csv: 
  REPARAT.csv: 
  REPARAT2.csv: 
  REPARHIST.csv: 
  REPDEF.csv: 
  REPERS.csv: 
  REPERSSER.csv: 
  REPFEHL.csv: 
  REPHELP.csv: 
  REPSICH.csv: 
  REPTEXTPOS.csv: 
  REPTXT.csv: 
  REPTYP.csv: 
  REPZUORD.csv: 
  ROHLOG.csv: 
  RUCKSEND.csv: 
  RUESTST.csv: 
  SACHKTO.csv: 
  SAMMRECH.csv: 
  SCANLOG.csv: 
  SCANPFAD.csv: 
  SCHABLON.csv: 
  SCHACHT.csv: 
  SCHICHT.csv: 
  SELEKTIO.csv: 
  SEMKO.csv: 
  SEMPO.csv: 
  SEMREF.csv: 
  SERDISPO.csv: 
  SERETI.csv: 
  SERIKOPF.csv: 
  SERIPOAH.csv: 
  SERIPOI.csv: 
  SERIPSN.csv: 
  SERIREKL.csv: 
  SERIZUOR.csv: 
  SERLKDRU.csv: 
  SERQS.csv: 
  SERRFERT.csv: 
  SERTMPAR.csv: 
  SERTMPBA.csv: 
  SERVBER.csv: 
  SERVRAUM.csv: 
  SERVZON.csv: 
  SERWB.csv: 
  SERWBVOR.csv: 
  SERWVERW.csv: 
  SETPO.csv: 
  SHORTCUT.csv: 
  SIEBLOG.csv: 
  SIGNATUR.csv: 
  SIGNIER.csv: 
  SLEISTE.csv: 
  SNSCHABL.csv: 
  SOLLIST.csv: 
  SONDERST.csv: 
  SONDINV.csv: 
  SPAETEK.csv: 
  SPAETVK.csv: 
  SPEDKO.csv: 
  SPERRLOG.csv: 
  SPEZIFIK.csv: 
  SPRDAT.csv: 
  STATIST.csv: 
  STULIPO.csv: 
  TAENDBST.csv: 
  TELEFONIE.csv: 
  TERMAEND.csv: 
  TERMINE.csv: 
  TEXTBST.csv: 
  TITEL.csv: 
  TOC_GF.csv: 
  TOC_WBZB.csv: 
  TOC_WBZS.csv: 
  TOOLBAR.csv: 
  TSGRU.csv: 
  TS_ARTIKEL.csv: 
  TS_SCHRANK.csv: 
  TS_SCHRANK_ARTIKEL.csv: 
  TYPEN.csv: 
  UGRUENDE.csv: 
  UGRUNTYP.csv: 
  UMA.csv: 
  UNTERLAGE.csv: 
  URSTEXT.csv: 
  USRGROUP.csv: 
  VARAPLA.csv: 
  VARSTULI.csv: 
  VERPACK.csv: 
  VERPACK2.csv: 
  VERPAKO.csv: 
  VERPAKTO.csv: 
  VERPAPO.csv: 
  VERTGEB.csv: 
  VERTST.csv: 
  VERTUMS.csv: 
  VORBMASS.csv: 
  VORLOG.csv: 
  VSTULI.csv: 
  VSWORKFL.csv: 
  WAEHRTAB.csv: 
  WARTTYP.csv: 
  WEPRFTXT.csv: 
  WEPRUEF.csv: 
  WERBCODE.csv: 
  WERKST.csv: 
  WERKZEUG.csv: 
  WETIMER.csv: 
  WEZERT.csv: 
  WGRUUMS.csv: 
  WIEDUSR.csv: 
  WKSLEBEN.csv: 
  WORKFLOW.csv: 
  WSTULI.csv: 
  WZLEBEN.csv: 
  ZAHLBED.csv: 
  ZEBUCH.csv: 
  ZEICHST.csv: 
  ZEITMZUO.csv: 
  ZEITRAB.csv: 
  ZEITST.csv: 
  ZOLLTAR.csv: 
  ZONEN.csv: 
  ZSTULI.csv: 
  ZULASS.csv: 
  ZULREF.csv: 
  ZUSCHLAEGE.csv: 
  ZUSCHLAG.csv: