file_mappings:
  ABBESTBEI.DBF:
  ABSENDER.DBF: 
  ABTEIL.DBF: 
  ADRESS.DBF: 
  AENDART.DBF: 
  AENDLOG.DBF: 
  AHAPLA.DBF: 
  AHLIEF.DBF: 
  ANABFMDE.DBF: 
  ANABMELD.DBF: 
  ANFKO.DBF: 
  ANFPO.DBF: 
  ANGKO.DBF: 
  ANGPO.DBF: 
  ANGTXT.DBF: 
  ANNAHMKO.DBF: 
  ANNAHMPO.DBF: 
  ANREDEN.DBF: 
  ANZRECH.DBF: 
  APLRUEST.DBF: 
  APLZSTAF.DBF: 
  APPAngko.DBF: 
  APPAngpo.DBF: 
  APPAufko.DBF: 
  APPAufpo.DBF: 
  APPUser.DBF: 
  ARBGANG.DBF: 
  ARBPLAPM.DBF: 
  ARBPLAPO.DBF: 
  ARBPLAWZN.DBF: 
  ARBPLPRS.DBF: 
  ARBTEXT.DBF: 
  ARCHUEB.DBF: 
  ARTDOK.DBF: 
  ARTGRU.DBF: 
  ARTKGRPR.DBF: 
  ARTKOMP.DBF: 
  ARTLEBEN.DBF: 
  ARTLIEF.DBF: 
  ARTSPERR.DBF: 
  ARTST.DBF: 
  ARTST2.DBF: 
  ARTSUCH.DBF: 
  AUFAEND.DBF: 
  AUFKO.DBF: 
  AUFPO.DBF: 
  AUFPOV.DBF: 
  AUFSCHL.DBF: 
  AUFSTAT.DBF: 
  AUFTERM.DBF: 
  AUFTXT.DBF: 
  AUSARB.DBF: 
  AUSFERKL.DBF: 
  AUSGRUND.DBF: 
  AUSLAST.DBF: 
  AUTOANF.DBF: 
  AUTOBEST.DBF: 
  AUTOBET.DBF: 
  AVWORKFL.DBF: 
  BAABGL.DBF: 
  BAAUSARB.DBF: 
  BAB.DBF: 
  BAKOMM.DBF: 
  BANKEN.DBF: 
  BARCODES.DBF: 
  BAVORBER.DBF: 
  BDEDAT.DBF: 
  BDELABEL.DBF: 
  BDEVERAG.DBF: 
  BDEVERS.DBF: 
  BELAKO.DBF: 
  BELAPO.DBF: 
  BELATXT.DBF: 
  BEMELD.DBF: 
  BEMELDBEI.DBF: 
  BEMELDLG.DBF: 
  BEMELDPO.DBF: 
  BEMELDV.DBF: 
  BEMELSER.DBF: 
  BEMELSNB.DBF: 
  BEMELUSB.DBF: 
  BEMELUSR.DBF: 
  BESTAEND.DBF: 
  BESTBEI.DBF: 
  BESTKO.DBF: 
  BESTPO.DBF: 
  BESTPO2.DBF: 
  BESTSTAT.DBF: 
  BESTTXT.DBF: 
  BETAPLA.DBF: 
  BETAPLAM.DBF: 
  BETAPLAS.DBF: 
  BETAPPRS.DBF: 
  BETAUF.DBF: 
  BETAUFAR.DBF: 
  BETAUFKO.DBF: 
  BETETI.DBF: 
  BETLIPLA.DBF: 
  BETMELD.DBF: 
  BETNACH.DBF: 
  BETPRUEF.DBF: 
  BETSTULI.DBF: 
  BILDARCH.DBF: 
  BLECH.DBF: 
  BLZST.DBF: 
  BRANCODE.DBF: 
  CAPAPOS.DBF: 
  CHAOSHIS.DBF: 
  CHAOSLAG.DBF: 
  CHARGEN.DBF: 
  CHARGRU.DBF: 
  CHARTXT.DBF: 
  CLCODE.DBF: 
  CRSMEDIA.DBF: 
  CSUPPKO.DBF: 
  CSUPPPO.DBF: 
  DATEVHLP.DBF: 
  DECKUNG.DBF: 
  DHRDAT.DBF: 
  DIGSIGLOG.DBF: 
  DISPOGRU.DBF: 
  DOKUMENT.DBF: 
  DOKUTEXT.DBF: 
  DPD.DBF: 
  DTVPRIMA.DBF: 
  EDIKOPF.DBF: 
  EDIORDK.DBF: 
  EDIORDP.DBF: 
  EDIORDT.DBF: 
  EDIPART.DBF: 
  EDIPOS.DBF: 
  EDIPROF.DBF: 
  EDITEXT.DBF: 
  EKGENOSS.DBF: 
  ENDPRUEF.DBF: 
  ENTBER.DBF: 
  ERSVER.DBF: 
  EXPTEXT.DBF: 
  EXTPRG.DBF: 
  FACHRICH.DBF: 
  FARTTXT.DBF: 
  FDANR.DBF: 
  FEHLKAT.DBF: 
  FEHLTAGE.DBF: 
  FEHLTEXT.DBF: 
  FEIERTAG.DBF: 
  FELDEINS.DBF: 
  FERTKO.DBF: 
  FRACHT.DBF: 
  FREMDREP.DBF: 
  GEBRPO.DBF: 
  GEBRST.DBF: 
  GELATXT.DBF: 
  GKVOR.DBF: 
  HAERTPR.DBF: 
  HANDBED.DBF: 
  HARBPLAPO.DBF: 
  HOTEL.DBF: 
  HPRUEFPO.DBF: 
  HRLAGER.DBF: 
  HSTULIPO.DBF: 
  IMPORTKO.DBF: 
  IMPORTPO.DBF: 
  IMPPROT.DBF: 
  INKASSO.DBF: 
  INTTEST.DBF: 
  INVLOG.DBF: 
  INVPERM.DBF: 
  JOB.DBF: 
  JOBPRIO.DBF: 
  KABELBW.DBF: 
  KALAPLA.DBF: 
  KALAPPRS.DBF: 
  KALEND2.DBF: 
  KALENDER.DBF: 
  KALKOPF2.DBF: 
  KALKULAT.DBF: 
  KALLEIST.DBF: 
  KALRUEST.DBF: 
  KALSTULI.DBF: 
  KALWERK.DBF: 
  KAPAPROF.DBF: 
  KAPFARB.DBF: 
  KDANF.DBF: 
  KDANFLOG.DBF: 
  KDERLKTO.DBF: 
  KDGRU.DBF: 
  KDGRURAB.DBF: 
  KDLIEF.DBF: 
  KDMASCH.DBF: 
  KDPARAM.DBF: 
  KDREF.DBF: 
  KDSPERR.DBF: 
  KDST.DBF: 
  KDST2.DBF: 
  KENNZTAB.DBF: 
  KONSILAG.DBF: 
  KONTAKTK.DBF: 
  KONTAKTL.DBF: 
  KONTBETR.DBF: 
  KONTBST.DBF: 
  KONZERN.DBF: 
  KORRMASS.DBF: 
  KOSTART.DBF: 
  KOSTGRU.DBF: 
  KOSTST.DBF: 
  KOSTTR.DBF: 
  KOSTWART.DBF: 
  KUNDANSP.DBF: 
  LAGER.DBF: 
  LAGHIST.DBF: 
  LAGPLATZ.DBF: 
  LAGPLPOS.DBF: 
  LANDTAB.DBF: 
  LEBENTXT.DBF: 
  LEIHHIPR.DBF: 
  LEIHHIST.DBF: 
  LEIHKOMP.DBF: 
  LEIHKOPR.DBF: 
  LEIHRESK.DBF: 
  LEIHRESP.DBF: 
  LEIHSEPR.DBF: 
  LEIHSET.DBF: 
  LFDNR1.DBF: 
  LFDNR2.DBF: 
  LFDNR3.DBF: 
  LGVERWEND.DBF: 
  LIEFADR.DBF: 
  LIEFANSP.DBF: 
  LIEFBED.DBF: 
  LIEFGRU.DBF: 
  LIEFKO.DBF: 
  LIEFPO.DBF: 
  LIEFPOC.DBF: 
  LIEFPOV.DBF: 
  LIEFRECH.DBF: 
  LIEFSPERR.DBF: 
  LIEFST.DBF: 
  LIEFSUCH.DBF: 
  LIEFTXT.DBF: 
  LIPLAPO.DBF: 
  LOGBUCH.DBF: 
  LOGPASS.DBF: 
  LOHNGRU.DBF: 
  MAHNLIEF.DBF: 
  MAHNLOG.DBF: 
  MAHNTXK2.DBF: 
  MAHNTXTD.DBF: 
  MAHNTXTK.DBF: 
  MASCHBLG.DBF: 
  MASCHFR.DBF: 
  MASCHGRU.DBF: 
  MASCHKO.DBF: 
  MASCHPLA.DBF: 
  MATKO.DBF: 
  MDEIMP.DBF: 
  MDEIMP2.DBF: 
  MENGTAB.DBF: 
  MENUSKIP.DBF: 
  MERKGRU.DBF: 
  MESSGER.DBF: 
  MESSGRU.DBF: 
  MESSKOST.DBF: 
  MINDMENG.DBF: 
  MOTIV.DBF: 
  MUSTER.DBF: 
  MWSTTAB.DBF: 
  NACHARB.DBF: 
  NOTIZ.DBF: 
  PARAHIST.DBF: 
  PASSWORT.DBF: 
  PAUSENST.DBF: 
  PDALOG.DBF: 
  PERLEBEN.DBF: 
  PERSGRU.DBF: 
  PERSONAL.DBF: 
  PGRUZUO.DBF: 
  PLZST.DBF: 
  PRODDOKU.DBF: 
  PRODMELD.DBF: 
  PRODPLA1.DBF: 
  PROGTAB.DBF: 
  PROJART.DBF: 
  PROJDOK.DBF: 
  PROJHIST.DBF: 
  PROJKO.DBF: 
  PROJPO.DBF: 
  PROJTEAM.DBF: 
  PROJZULA.DBF: 
  PROVSTAF.DBF: 
  PRUEFANW.DBF: 
  PRUEFBDE.DBF: 
  PRUEFHIS.DBF: 
  PRUEFPO.DBF: 
  PZELABEL.DBF: 
  PZESALDO.DBF: 
  QUALIFIK.DBF: 
  QUARUMS.DBF: 
  RABATTE.DBF: 
  RECHKO.DBF: 
  RECHPO.DBF: 
  RECHTXT.DBF: 
  REFUEB.DBF: 
  REPARAT.DBF: 
  REPARAT2.DBF: 
  REPARHIST.DBF: 
  REPDEF.DBF: 
  REPERS.DBF: 
  REPERSSER.DBF: 
  REPFEHL.DBF: 
  REPHELP.DBF: 
  REPSICH.DBF: 
  REPTEXTPOS.DBF: 
  REPTXT.DBF: 
  REPTYP.DBF: 
  REPZUORD.DBF: 
  ROHLOG.DBF: 
  RUCKSEND.DBF: 
  RUESTST.DBF: 
  SACHKTO.DBF: 
  SAMMRECH.DBF: 
  SCANLOG.DBF: 
  SCANPFAD.DBF: 
  SCHABLON.DBF: 
  SCHACHT.DBF: 
  SCHICHT.DBF: 
  SELEKTIO.DBF: 
  SEMKO.DBF: 
  SEMPO.DBF: 
  SEMREF.DBF: 
  SERDISPO.DBF: 
  SERETI.DBF: 
  SERIKOPF.DBF: 
  SERIPOAH.DBF: 
  SERIPOI.DBF: 
  SERIPSN.DBF: 
  SERIREKL.DBF: 
  SERIZUOR.DBF: 
  SERLKDRU.DBF: 
  SERQS.DBF: 
  SERRFERT.DBF: 
  SERTMPAR.DBF: 
  SERTMPBA.DBF: 
  SERVBER.DBF: 
  SERVRAUM.DBF: 
  SERVZON.DBF: 
  SERWB.DBF: 
  SERWBVOR.DBF: 
  SERWVERW.DBF: 
  SETPO.DBF: 
  SHORTCUT.DBF: 
  SIEBLOG.DBF: 
  SIGNATUR.DBF: 
  SIGNIER.DBF: 
  SLEISTE.DBF: 
  SNSCHABL.DBF: 
  SOLLIST.DBF: 
  SONDERST.DBF: 
  SONDINV.DBF: 
  SPAETEK.DBF: 
  SPAETVK.DBF: 
  SPEDKO.DBF: 
  SPERRLOG.DBF: 
  SPEZIFIK.DBF: 
  SPRDAT.DBF: 
  STATIST.DBF: 
  STULIPO.DBF: 
  TAENDBST.DBF: 
  TELEFONIE.DBF: 
  TERMAEND.DBF: 
  TERMINE.DBF: 
  TEXTBST.DBF: 
  TITEL.DBF: 
  TOC_GF.DBF: 
  TOC_WBZB.DBF: 
  TOC_WBZS.DBF: 
  TOOLBAR.DBF: 
  TSGRU.DBF: 
  TS_ARTIKEL.DBF: 
  TS_SCHRANK.DBF: 
  TS_SCHRANK_ARTIKEL.DBF: 
  TYPEN.DBF: 
  UGRUENDE.DBF: 
  UGRUNTYP.DBF: 
  UMA.DBF: 
  UNTERLAGE.DBF: 
  URSTEXT.DBF: 
  USRGROUP.DBF: 
  VARAPLA.DBF: 
  VARSTULI.DBF: 
  VERPACK.DBF: 
  VERPACK2.DBF: 
  VERPAKO.DBF: 
  VERPAKTO.DBF: 
  VERPAPO.DBF: 
  VERTGEB.DBF: 
  VERTST.DBF: 
  VERTUMS.DBF: 
  VORBMASS.DBF: 
  VORLOG.DBF: 
  VSTULI.DBF: 
  VSWORKFL.DBF: 
  WAEHRTAB.DBF: 
  WARTTYP.DBF: 
  WEPRFTXT.DBF: 
  WEPRUEF.DBF: 
  WERBCODE.DBF: 
  WERKST.DBF: 
  WERKZEUG.DBF: 
  WETIMER.DBF: 
  WEZERT.DBF: 
  WGRUUMS.DBF: 
  WIEDUSR.DBF: 
  WKSLEBEN.DBF: 
  WORKFLOW.DBF: 
  WSTULI.DBF: 
  WZLEBEN.DBF: 
  ZAHLBED.DBF: 
  ZEBUCH.DBF: 
  ZEICHST.DBF: 
  ZEITMZUO.DBF: 
  ZEITRAB.DBF: 
  ZEITST.DBF: 
  ZOLLTAR.DBF: 
  ZONEN.DBF: 
  ZSTULI.DBF: 
  ZULASS.DBF: 
  ZULREF.DBF: 
  ZUSCHLAEGE.DBF: 
  ZUSCHLAG.DBF: