Einkaufsteile:
  Zeichnungsteile:
    Laserteil:
      checkbox 1: laserschneiden
      checkbox 2: ', abkanten'
      checkbox 3: ', inklusive Material'
      checkbox 4: ', Gewindeschneiden'
      Bezeichnungselemente:
      - checkbox 1
      - checkbox 2
      - checkbox 3
      - checkbox 4
    Mechanisches Teil:
      checkbox 1: komplett fertigen
      checkbox 2: ', Fräsen'
      checkbox 3: ', Drehen'
      checkbox 4: ', Schweißen'
      checkbox 5: ', inklusive Material'
      Bezeichnungselemente:
      - checkbox 1
      - checkbox 2
      - checkbox 3
      - checkbox 4
      - checkbox 5
    Listenteile: null
  Normteile:
    Normteile: null
    Schrauben Metrisch / Sechskantschraube: null
    Schrauben Metrisch / Zylinderschraube: null
    Schrauben Metrisch / Senkschraube: null
    Unterlegscheiben / Federring: null
    Unterlegscheiben / Passscheibe: null
    Unterlegscheiben / Unterlegscheibe: null
    Unterlegscheiben / Unterlegscheibe mit Fase: null
    Muttern / Sechskantmutter: null
    Muttern / Flügelmutter: null
    Muttern / Sechskant-Sicherungsmutter: null
    Blindnietmuttern: null
    Blindnieten: null
    Gewindestift: null
    Blindnietmutter: null
    Gewindestifte: null
    Stellringe: null
    Schrauben Metrisch / Senkkopfschraube: null
    Sicherungsring für Welle: null
    Passcheibe: null
    Spannhülse schwer: null
    Flügelschraube: null
  Listenteile:
    Standard: null
    Passcheibe: null
  Rohmaterial:
    Blech: null
    Rohr: null
    Rundstahl: null
Produktionsteile:
  Produktionsteil:
    Standard: null
Verkaufsteile:
  Verkaufsoptionsteile:
    standard: null
  Verkaufsprodukt:
    Standard: null
Serviceteile: null
